### ISSUE TITLE
Run "M-x svnwiki-mode" in the second time, it is not disable svnwiki-mode for the file in *\wiki\eggref\5\ folder

### ISSUE THREAD

**Issue by APIPLM** [chicken-contrib/svnwiki-mode#2]
After installing the svnwiki-mode by loading the `svnwiki-mode.el ` file.  Open the file in  *\wiki\eggref\5\ folder, then run `M-x svnwiki-mode`, then the run command again. The current buffer is still in svnwiki-mode.

**Comment by wasamasa** [comment]
It's a major mode, not a minor mode. This is expected behavior. To quote the Emacs manual:

>    Usually, the major mode is automatically set by Emacs, when you first
visit a file or create a buffer (*note Choosing Modes::).  You can
explicitly select a new major mode by using an ‘M-x’ command.  Take the
name of the mode and add ‘-mode’ to get the name of the command to
select that mode (e.g., ‘M-x lisp-mode’ enters Lisp mode).  **Since every
buffer has exactly one major mode, there is no way to “turn off” a major
mode; instead you must switch to a different one.**

**Comment by APIPLM** [comment]
Thank for your quick reply.
